<?php $_order = $this->getOrder(); ?>
<?php if(!$_order->getCustomerIsGuest()): ?>
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "EmailMessage",
  "description": "<?php echo Mage::getStoreConfig("meanbee_gmailactions_options/order_email/description"); ?>",
  "action": {
    "@type": "ViewAction",
    "url": "<?php echo $this->getViewOrderUrl($_order); ?>",
    "name": "<?php echo Mage::getStoreConfig("meanbee_gmailactions_options/order_email/action_name"); ?>"
  }
}
</script>
<?php endif; ?>