<?php $_shipment = $this->getShipment(); ?>
<?php $_order = $this->getOrder(); ?>
<?php if ($_order->getCustomerIsGuest() == 0): ?>
<script type="application/ld+json">
{
  "@context": "http://schema.org",
  "@type": "EmailMessage",
  "description": "<?php echo Mage::getStoreConfig("meanbee_gmailactions_options/shipment_email/description"); ?>",
  "action": {
    "@type": "ViewAction",
    "url": "<?php echo $this->getViewShipmentUrl($_order); ?>",
    "name": "<?php echo Mage::getStoreConfig("meanbee_gmailactions_options/shipment_email/action_name"); ?>"
  }
}
</script>
<?php endif; ?>